-- Active: 1712051663122@@127.0.0.1@3306@coin_exchange

CREATE DATABASE IF NOT EXISTS coin_exchange DEFAULT CHARACTER SET = 'utf8mb4';

CREATE TABLE IF NOT EXISTS `member` (
    `id` BIGINT(0) NOT NULL AUTO_INCREMENT,
    `ali_no` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
    `qr_code_url` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
    `appeal_success_times` INT(0) NOT NULL,
    `appeal_times` INT(0) NOT NULL,
    `application_time` BIGINT(0) NOT NULL,
    `avatar` VARCHAR(255) NOT NULL,
    `bank` VARCHAR(255) NOT NULL,
    `branch` VARCHAR(255) NOT NULL,
    `card_no` VARCHAR(255) NOT NULL,
    `certified_business_apply_time` BIGINT(0) NOT NULL,
    `certified_business_check_time` BIGINT(0),
    `certified_business_status` INT(0),
    `channel_id` INT(0) NOT NULL DEFAULT 0,
    `email` VARCHAR(255) NOT NULL,
    `first_level` INT(0) NOT NULL,
    `google_date` BIGINT(0) NOT NULL,
    `goole_key` VARCHAR(255) NOT NULL,
    `google_state` INT(0) NOT NULL DEFAULT 0,
    `id_number` VARCHAR(255) NOT NULL,
    `inviter_id` BIGINT(0) NOT NULL,
    `is_channel` INT(0) NOT NULL DEFAULT 0,
    `jy_password` VARCHAR(255) NOT NULL,
    `last_login_time` BIGINT(0) NOT NULL,
    `city` VARCHAR(255) NOT NULL,
    `country` VARCHAR(255) NOT NULL,
    `district` VARCHAR(255) NOT NULL,
    `province` VARCHAR(255) NOT NULL,
    `login_count` INT(0) NOT NULL,
    `login_lock` INT(0) NOT NULL,
    `margin` VARCHAR(255) NOT NULL,
    `member_level` INT(0) NOT NULL,
    `mobile_phone` VARCHAR(255) NOT NULL,
    `password` VARCHAR(255) NOT NULL,
    `promotion_code` VARCHAR(255) NOT NULL,
    `publish_advertise` INT(0) NOT NULL,
    `real_name` VARCHAR(255) NOT NULL,
    `real_name_status` INT(0) NOT NULL,
    `registration_time` BIGINT(0) NOT NULL,
    `salt` VARCHAR(255) NOT NULL,
    `second_level` INT(0) NOT NULL,
    `sign_in_ability` TINYINT(4) NOT NULL,
    `status` INT(0) NOT NULL,
    `third_level` INT(0) NOT NULL,
    `token` VARCHAR(255) NOT NULL,
    `token_expire_time` BIGINT(0) NOT NULL,
    `transaction_status` INT(0) NOT NULL,
    `transaction_time` BIGINT(0) NOT NULL,
    `transactions` INT(0) NOT NULL,
    `username` VARCHAR(255) NOT NULL,
    `qr_we_code_url` VARCHAR(255) NOT NULL,
    `wechat` VARCHAR(255) NOT NULL,
    `local` VARCHAR(255) NOT NULL,
    `integration` BIGINT(0) NOT NULL DEFAULT 0,
    `member_grade_id` BIGINT(0) NOT NULL COMMENT '等级id',
    `kys_status` INT(0) NOT NULL COMMENT 'kyc等级',
    `generalize_total` BIGINT(0) NOT NULL DEFAULT 0 COMMENT '注册赠送积分',
    `inviter_parent_id` BIGINT(0) NOT NULL DEFAULT 0,
    `super_partner` VARCHAR(255) NOT NULL,
    `kick_fee` DECIMAL(19, 2) NOT NULL,
    `power` DECIMAL(8, 4) NOT NULL DEFAULT 0.0000 COMMENT '个人矿机算力（每日维护）',
    `team_level` INT(0) NOT NULL DEFAULT 0 COMMENT '团队人数（每日维护）',
    `team_power` DECIMAL(8, 4) NOT NULL DEFAULT 0.0000 COMMENT '团队框架算力（每日维护）',
    `member_level_id` BIGINT(0) NOT NULL,
    PRIMARY KEY (`id`) USING BTREE,
    UNIQUE INDEX `uk_username` (`username`) USING BTREE,
    UNIQUE INDEX `uk_mobile_phone` (`mobile_phone`) USING BTREE,
    INDEX `fk_local` (`local`) USING BTREE,
    INDEX `fk_member_level_id` (`member_level_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4