// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2

package types

type Request struct {
	UserName string `json:"username"`
	Password string `json:"password"`
	Captcha string `json:"captcha"`
	Phone string `json:"phone"`
	Promotion string `json:"promotion"`
	Code string `json:"code"`
	Country string `json:"country"`
	SuperPartner string `json:"superpartner"`
	Ip string `json:"ip,optional"`
}

type Response struct {
	Message string `json:"message"`
}


type CodeRequest struct {
	Phone string `json:"phone"`
	Country string `json:"country"`
}

type CodeResponse struct{

}
