// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2
package handler

import (
	"github.com/wushengyouya/coin_exchange/ucenter-api/internal/svc"
)


func RegisterHandlers(r *Routers, serverCtx *svc.ServiceContext) {
	register:=NewRegisterHandler(serverCtx)
	registerRouter:=r.Group()

	registerRouter.Get("/uc/register/phone",register.Register)
	registerRouter.Post("/uc/mobile/code",register.SendCode)
}
